name: flock
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies:
  resource_importer: ^0.1.0+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


resource_importer:
  resources:
    schedulerTemplate: 
      path: 'assets/templates/scheduler.template'
      type: String

    objectTemplate: 
      path: 'assets/templates/object.template'
      type: String

    restTemplate: 
      path: 'assets/templates/rest.template'
      type: String

    mapExpTemplate: 
      path: 'assets/templates/map-exp.template'
      type: String